# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: glossary.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'glossary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eglossary.proto\x12\x08glossary\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0bTermRequest\x12\x11\n\tterm_name\x18\x01 \x01(\t\"8\n\x10RelationsRequest\x12\x11\n\tterm_name\x18\x01 \x01(\t\x12\x11\n\tmax_depth\x18\x02 \x01(\x05\"J\n\x0bPathRequest\x12\x13\n\x0bsource_term\x18\x01 \x01(\t\x12\x13\n\x0btarget_term\x18\x02 \x01(\t\x12\x11\n\tmax_depth\x18\x03 \x01(\x05\"(\n\x04Term\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\ndefinition\x18\x02 \x01(\t\"K\n\x08Relation\x12\x13\n\x0bsource_term\x18\x01 \x01(\t\x12\x13\n\x0btarget_term\x18\x02 \x01(\t\x12\x15\n\rrelation_type\x18\x03 \x01(\t\";\n\x0cTermResponse\x12\x1c\n\x04term\x18\x01 \x01(\x0b\x32\x0e.glossary.Term\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"O\n\x11RelationsResponse\x12%\n\trelations\x18\x01 \x03(\x0b\x32\x12.glossary.Relation\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\"B\n\x0cPathResponse\x12\x0c\n\x04path\x18\x01 \x03(\t\x12\x13\n\x0bpath_exists\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"F\n\x10\x41llTermsResponse\x12\x1d\n\x05terms\x18\x01 \x03(\x0b\x32\x0e.glossary.Term\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\x96\x02\n\x0fGlossaryService\x12\x38\n\x07GetTerm\x12\x15.glossary.TermRequest\x1a\x16.glossary.TermResponse\x12\x41\n\x0bGetAllTerms\x12\x16.google.protobuf.Empty\x1a\x1a.glossary.AllTermsResponse\x12K\n\x10GetTermRelations\x12\x1a.glossary.RelationsRequest\x1a\x1b.glossary.RelationsResponse\x12\x39\n\x08\x46indPath\x12\x15.glossary.PathRequest\x1a\x16.glossary.PathResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'glossary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TERMREQUEST']._serialized_start=57
  _globals['_TERMREQUEST']._serialized_end=89
  _globals['_RELATIONSREQUEST']._serialized_start=91
  _globals['_RELATIONSREQUEST']._serialized_end=147
  _globals['_PATHREQUEST']._serialized_start=149
  _globals['_PATHREQUEST']._serialized_end=223
  _globals['_TERM']._serialized_start=225
  _globals['_TERM']._serialized_end=265
  _globals['_RELATION']._serialized_start=267
  _globals['_RELATION']._serialized_end=342
  _globals['_TERMRESPONSE']._serialized_start=344
  _globals['_TERMRESPONSE']._serialized_end=403
  _globals['_RELATIONSRESPONSE']._serialized_start=405
  _globals['_RELATIONSRESPONSE']._serialized_end=484
  _globals['_PATHRESPONSE']._serialized_start=486
  _globals['_PATHRESPONSE']._serialized_end=552
  _globals['_ALLTERMSRESPONSE']._serialized_start=554
  _globals['_ALLTERMSRESPONSE']._serialized_end=624
  _globals['_GLOSSARYSERVICE']._serialized_start=627
  _globals['_GLOSSARYSERVICE']._serialized_end=905
# @@protoc_insertion_point(module_scope)
