# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import glossary_pb2 as glossary__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in glossary_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GlossaryServiceStub(object):
    """Сервис для работы с графом терминов
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTerm = channel.unary_unary(
                '/glossary.GlossaryService/GetTerm',
                request_serializer=glossary__pb2.TermRequest.SerializeToString,
                response_deserializer=glossary__pb2.TermResponse.FromString,
                _registered_method=True)
        self.GetAllTerms = channel.unary_unary(
                '/glossary.GlossaryService/GetAllTerms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=glossary__pb2.AllTermsResponse.FromString,
                _registered_method=True)
        self.GetTermRelations = channel.unary_unary(
                '/glossary.GlossaryService/GetTermRelations',
                request_serializer=glossary__pb2.RelationsRequest.SerializeToString,
                response_deserializer=glossary__pb2.RelationsResponse.FromString,
                _registered_method=True)
        self.FindPath = channel.unary_unary(
                '/glossary.GlossaryService/FindPath',
                request_serializer=glossary__pb2.PathRequest.SerializeToString,
                response_deserializer=glossary__pb2.PathResponse.FromString,
                _registered_method=True)


class GlossaryServiceServicer(object):
    """Сервис для работы с графом терминов
    """

    def GetTerm(self, request, context):
        """Получить информацию о термине
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTerms(self, request, context):
        """Получить все термины
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTermRelations(self, request, context):
        """Получить связи термина (соседи в графе)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindPath(self, request, context):
        """Найти путь между двумя терминами
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GlossaryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTerm,
                    request_deserializer=glossary__pb2.TermRequest.FromString,
                    response_serializer=glossary__pb2.TermResponse.SerializeToString,
            ),
            'GetAllTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTerms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=glossary__pb2.AllTermsResponse.SerializeToString,
            ),
            'GetTermRelations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTermRelations,
                    request_deserializer=glossary__pb2.RelationsRequest.FromString,
                    response_serializer=glossary__pb2.RelationsResponse.SerializeToString,
            ),
            'FindPath': grpc.unary_unary_rpc_method_handler(
                    servicer.FindPath,
                    request_deserializer=glossary__pb2.PathRequest.FromString,
                    response_serializer=glossary__pb2.PathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'glossary.GlossaryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('glossary.GlossaryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GlossaryService(object):
    """Сервис для работы с графом терминов
    """

    @staticmethod
    def GetTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetTerm',
            glossary__pb2.TermRequest.SerializeToString,
            glossary__pb2.TermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetAllTerms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            glossary__pb2.AllTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTermRelations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/GetTermRelations',
            glossary__pb2.RelationsRequest.SerializeToString,
            glossary__pb2.RelationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/glossary.GlossaryService/FindPath',
            glossary__pb2.PathRequest.SerializeToString,
            glossary__pb2.PathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
